services:
    wordpress:
        container_name: wordpress
        build: ./wordpress
        volumes:
            - nginx_wp:/var/www/html
        networks:
            - inception
        env_file: ../.env
        restart: unless-stopped
        secrets:
            - wpadminpwd
            - dbpassword
        depends_on:
            mariadb:
                condition: service_healthy

    mariadb:
        container_name: mariadb
        build:
            context: ./mariadb
            args:
                - MARIADB_CONFIG_FILE=mariadb_config_file.txt
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - inception
        env_file:
            - ../.env
        secrets:
            - dbpassword
            - dbrootpassword
        restart: unless-stopped
    
    nginx:
        container_name: nginx
        build: ./nginx
        volumes:
            - nginx_wp:/
        ports:
            - "443:443"
        networks:
            - inception
        env_file:
            - ../.env
        restart: unless-stopped
        depends_on:
            - wordpress

networks:
    inception:
        driver: bridge

volumes:
    mariadb:
        name: mariadb_volume
    nginx_wp:
        name: wp_volume
    

secrets:
    dbpassword:
        file: ../secrets/db_password.txt
    dbrootpassword:
        file: ../secrets/db_root_password.txt
    wpadminpwd:
        file: ../secrets/wp_admin_password.txt

